### ISSUE TITLE
Some compiler errors because of usage of some c# 9 elements in version below 2021.2

### ISSUE THREAD

**Issue by popcron** [Chizaruu/com.unity.ide.vscode#59]
### Current Behavior

Title. Most of the errors thrown were due to `new()` and maybe `is not null` but havent seen all of the errors, this leaves me unable to import this into older dinosaur projects.
<details>
  <summary>Log from console window</summary>

  ```
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\AssemblyNameProvider.cs(37,36): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(42,17): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\AssemblyNameProvider.cs(37,37): error CS1526: A new expression requires (), [], or {} after type
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(375,69): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(375,70): error CS1526: A new expression requires (), [], or {} after type
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(621,24): error CS1031: Type expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(621,24): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(621,24): error CS1026: ) expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(621,24): error CS1526: A new expression requires (), [], or {} after type
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(621,24): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(622,35): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(622,35): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(623,58): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(623,58): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(624,63): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(624,63): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(634,24): error CS1031: Type expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(634,24): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(634,24): error CS1026: ) expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(634,24): error CS1526: A new expression requires (), [], or {} after type
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(634,24): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(635,35): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(635,35): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(636,58): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(636,58): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(637,63): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(637,63): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(638,53): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(638,53): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(639,97): error CS1002: ; expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(639,97): error CS1513: } expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(679,45): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(680,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(680,39): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(681,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(681,51): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(682,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(682,51): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(683,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(683,52): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(684,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(684,43): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(685,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(685,59): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(686,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(686,50): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(687,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(687,46): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(688,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(688,46): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(689,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(689,48): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(690,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(690,42): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(691,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(691,52): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(692,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(692,31): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(693,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(693,43): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(694,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(694,51): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(695,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(695,42): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(696,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(696,53): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(697,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(697,33): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(698,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(698,45): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(699,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(699,37): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(700,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(700,43): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(701,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(701,40): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(702,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(702,40): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(703,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(703,39): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(704,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(704,50): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(705,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(705,50): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(706,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(706,54): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(707,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(707,36): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(708,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(708,47): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(709,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(709,44): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(710,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(710,52): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(711,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(711,71): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(712,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(712,45): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(713,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(713,61): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(714,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(714,59): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(715,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(715,61): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(716,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(716,67): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(717,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(717,42): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(718,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(718,53): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(719,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(719,52): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(720,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(720,38): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(721,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(721,44): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(722,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(722,53): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(723,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(723,45): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(724,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(724,49): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(725,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(725,44): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(726,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(726,39): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(727,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(727,45): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(728,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(728,42): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(729,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(729,44): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(730,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(730,46): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(731,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(731,38): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(732,20): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(921,20): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(921,56): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(922,41): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(922,41): error CS1525: Invalid expression term '.'
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(922,49): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(923,41): error CS1003: Syntax error, '=>' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(923,41): error CS1525: Invalid expression term '.'
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(923,51): error CS1003: Syntax error, ',' expected
Library\PackageCache\com.tsk.ide.vscode@1f28589b99\Editor\ProjectGeneration\ProjectGeneration.cs(923,51): error CS8504: Pattern missing
```

</details>

### Reproduction / Steps To Reproduce

1. Import while using unity 2021.2

**Comment by popcron** [comment]
[made the changes](https://github.com/popcron/com.tsk.ide.vscode/tree/upm) needed and it works, though autocomplete/intellisense doesnt seem to work (nbd, probably something to do either with omnisharp or standard2.0 or both)

**Comment by Chizaruu** [comment]
Cool, you got it working with 2020.2 😄

But can I ask why you want to use my package over Unity's package for 2020? 🤔

**Comment by Chizaruu** [comment]
Please note that this package will not support Unity versions prior to 2021.3, as indicated in the [CHANGELOG](https://github.com/Chizaruu/com.tsk.ide.vscode/blob/default/com.tsk.ide.vscode/CHANGELOG.md#134---2023-04-07).
